export const PRODUCTS = [
  {
    id: 1,
    name: "Мёд таёжный цветочный",
    price: 650,
    oldPrice: 800,
    rating: 4.9,
    reviews: 142,
    badge: "city",
    city: "Новосибирске",
    image: "https://cdn.poehali.dev/projects/30e9900d-06e6-4571-878c-34078a0fc414/files/f08a55f9-b6e6-4858-aa68-bce98ed90517.jpg",
    shop: "Пасека Никитиных",
    shopAvatar: "🍯",
    inFav: false,
  },
  {
    id: 2,
    name: "Хлеб «Деревенский» на закваске",
    price: 280,
    oldPrice: null as number | null,
    rating: 4.8,
    reviews: 89,
    badge: "rf",
    city: "",
    image: "https://cdn.poehali.dev/projects/30e9900d-06e6-4571-878c-34078a0fc414/files/5ea90587-6bc1-4300-ae95-4c07fbf34c62.jpg",
    shop: "Пекарня «Заквас»",
    shopAvatar: "🍞",
    inFav: true,
  },
  {
    id: 3,
    name: "Керамическая миска ручной работы",
    price: 1200,
    oldPrice: 1500 as number | null,
    rating: 5.0,
    reviews: 37,
    badge: "city",
    city: "Екатеринбурге",
    image: "https://cdn.poehali.dev/projects/30e9900d-06e6-4571-878c-34078a0fc414/files/252d1ec6-fd5a-46f8-8438-1304e2572bcf.jpg",
    shop: "Мастерская Глины",
    shopAvatar: "🏺",
    inFav: false,
  },
  {
    id: 4,
    name: "Овощи с грядки: томаты и зелень",
    price: 180,
    oldPrice: null as number | null,
    rating: 4.7,
    reviews: 215,
    badge: "city",
    city: "Краснодаре",
    image: "https://cdn.poehali.dev/projects/30e9900d-06e6-4571-878c-34078a0fc414/files/52b551fc-7747-4258-a60b-8a638f85df55.jpg",
    shop: "Ферма Солнечная",
    shopAvatar: "🌱",
    inFav: false,
  },
  {
    id: 5,
    name: "Свеча соевая «Лес после дождя»",
    price: 450,
    oldPrice: 600 as number | null,
    rating: 4.9,
    reviews: 68,
    badge: "rf",
    city: "",
    image: "https://cdn.poehali.dev/projects/30e9900d-06e6-4571-878c-34078a0fc414/files/a92a5327-b3a6-4e89-be10-479d08061f9b.jpg",
    shop: "Candle Studio",
    shopAvatar: "🕯️",
    inFav: true,
  },
  {
    id: 6,
    name: "Кошелёк кожаный ручной выделки",
    price: 2800,
    oldPrice: null as number | null,
    rating: 4.8,
    reviews: 54,
    badge: "rf",
    city: "",
    image: "https://cdn.poehali.dev/projects/30e9900d-06e6-4571-878c-34078a0fc414/files/8d550188-c40d-4c29-97a3-bf9479983a3b.jpg",
    shop: "Мастер Кожи",
    shopAvatar: "👜",
    inFav: false,
  },
];

export const SHOPS = [
  { id: 1, name: "Пасека Никитиных", category: "Еда", avatar: "🍯", rating: 4.9, products: 24, verified: true, color: "#fff3d0" },
  { id: 2, name: "Пекарня «Заквас»", category: "Еда", avatar: "🍞", rating: 4.8, products: 18, verified: true, color: "#e0f7fd" },
  { id: 3, name: "Мастерская Глины", category: "Хендмейд", avatar: "🏺", rating: 5.0, products: 42, verified: true, color: "#fce8e8" },
  { id: 4, name: "Ферма Солнечная", category: "Эко", avatar: "🌱", rating: 4.7, products: 67, verified: false, color: "#e8f5e0" },
  { id: 5, name: "Candle Studio", category: "Дом", avatar: "🕯️", rating: 4.9, products: 31, verified: true, color: "#f0eaff" },
  { id: 6, name: "Мастер Кожи", category: "Мода", avatar: "👜", rating: 4.8, products: 15, verified: true, color: "#ffeee0" },
  { id: 7, name: "Цветочный двор", category: "Цветы", avatar: "🌸", rating: 4.9, products: 88, verified: true, color: "#fce8f0" },
  { id: 8, name: "Сырная лавка", category: "Еда", avatar: "🧀", rating: 4.6, products: 12, verified: false, color: "#fffbe0" },
];

export const CATEGORIES = [
  { icon: "🍎", label: "Еда и напитки" },
  { icon: "🌿", label: "Эко-товары" },
  { icon: "🏺", label: "Хендмейд" },
  { icon: "🌸", label: "Красота" },
  { icon: "🏠", label: "Дом и уют" },
];

export const REVIEWS = [
  {
    id: 1,
    name: "Ольга М.",
    avatar: "О",
    text: "Заказываю уже третий раз — всё свежее, упаковка аккуратная. Наконец-то платформа, где можно поддержать местных!",
    rating: 5,
    date: "2 дня назад",
  },
  {
    id: 2,
    name: "Андрей К.",
    avatar: "А",
    text: "Нашёл пекаря из своего района. Хлеб лучший в жизни. Рекомендую всем!",
    rating: 5,
    date: "5 дней назад",
  },
  {
    id: 3,
    name: "Марина Д.",
    avatar: "М",
    text: "Отличный сервис, удобный поиск по городу. Купила керамику в подарок — все в восторге.",
    rating: 4,
    date: "1 неделю назад",
  },
];
